// --------------------------------------------------------------
// 附录 B：英译中术语映射
// 移植自 scripts/clean_segments_v2_demo.py
// --------------------------------------------------------------

export const TERM_MAP: Record<string, string> = {
  "FPS": "FPS",
  "PVP": "PVP",
  "PVE": "PVE",
  "MMO": "MMO",
  "MOBA": "MOBA",
  "RPG": "RPG",
  "battle royale": "大逃杀",
  "extraction shooter": "搜打撤",
  "hero shooter": "英雄射击",
  "tactical shooter": "战术射击",
  "PC": "PC",
  "console": "主机",
  "mobile": "手机",
  "single player": "单机",
  "multiplayer": "多人",
  "co-op": "合作",
  "competitive": "竞技",
  "casual": "休闲",
  "ranked": "排位",
  "solo": "单排",
  "duo": "双排",
  "squad": "组队",
  "clan": "公会",
  "guild": "公会",
  "P2W": "氪金变强",
  "pay to win": "氪金变强",
  "free to play": "免费",
  "battle pass": "战令",
  "loot box": "开箱",
  "gacha": "抽卡",
  "grind": "肝",
  "noob": "新手",
  "pro": "高手",
  "carry": "带飞",
  "cheater": "外挂",
  "hacker": "外挂",
  "bug": "Bug",
  "glitch": "Bug",
  "lag": "卡顿",
  "smurf": "炸鱼",
  "boost": "代练",
  "patch": "补丁",
  "update": "更新",
  "DLC": "DLC",
  "MOD": "MOD",
  "UGC": "UGC",
  "NPC": "NPC",
  "meta": "Meta",
  "nerf": "削弱",
  "buff": "Buff",
  "skin": "皮肤",
  "gear": "装备",
  "loot": "掉落",
  "raid": "团本",
  "quest": "任务",
  "open world": "开放世界",
  "survival": "生存",
  "horror": "恐怖",
  "stealth": "潜行",
  "shooter": "射击",
  "gunplay": "枪感",
  "aiming": "瞄准",
  "recoil": "后坐力",
  "headshot": "爆头",
  "rank": "段位",
  "matchmaking": "匹配",
};

/** 术语匹配顺序：长术语优先 */
export const TERM_KEYS: string[] = Object.keys(TERM_MAP).sort(
  (a, b) => b.length - a.length,
);